project:
  type: website
  output-dir: docs

website:
  title: "Jan Freihardt"
  site-url: "https://janfreihardt.github.io/website/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

