---
title: "Media"
format:
  html:
    toc: false
---

::: {.section-intro}
My research on environmental (im)mobility and climate change has been covered by a range of international media outlets. Below is a selection of press coverage, radio features, and podcast appearances.
:::

## Press & Radio

<ul class="media-list">

<li>
<span class="media-outlet">Dawn</span><span class="media-date">09 Apr 2026</span><br>
[German scholar highlights data gap on climate-affected populations in Pakistan](https://www.dawn.com/news/1990085/german-scholar-highlights-data-gap-on-climate-affected-populations-in-pakistan)
</li>

<li>
<span class="media-outlet">SRF</span><span class="media-date">29 Mar 2026</span><br>
[Klimamigration unter der Lupe: Wenn das eigene Haus weggespült wird](https://www.srf.ch/wissen/klimawandel/klimamigration-unter-der-lupe-wenn-das-eigene-haus-weggespuelt-wird)
</li>

<li>
<span class="media-outlet">SRF</span><span class="media-date">23 Mar 2026</span><br>
[«Echo Wissen»: Warum Prognosen zu Klimamigration schwierig sind](https://www.srf.ch/audio/echo-der-zeit/echo-wissen-warum-prognosen-zu-klimamigration-schwierig-sind?partId=ICW6-FCRZWf6EGUnF4XpYI9xk3E)
</li>

<li>
<span class="media-outlet">The Hindu</span><span class="media-date">14 Jul 2025</span><br>
[Climate change is changing where and how Indians are living](https://www.thehindu.com/sci-tech/energy-and-environment/climate-change-internal-migration-changing-where-how-indians-living/article69807089.ece)
</li>

<li>
<span class="media-outlet">GoodImpact</span><span class="media-date">30 Jun 2025</span><br>
[Im Bann des gefräßigen Flusses](https://goodimpact.eu/recherche/im-bann-des-gefrasigen-flusses/)
</li>

<li>
<span class="media-outlet">SRF</span><span class="media-date">2 Mar 2025</span><br>
[Der Klimawandel erzeugt kaum Migration ins Ausland](https://www.srf.ch/news/dialog/eth-studie-zu-bangladesch-der-klimawandel-erzeugt-kaum-migration-ins-ausland)
</li>

<li>
<span class="media-outlet">Swissinfo</span><span class="media-date">27 Feb 2025</span><br>
[Der Klimawandel beeinflusst die Migration nicht immer so, wie man denkt – das Beispiel Bangladesch](https://www.swissinfo.ch/ger/aussenpolitik/der-klimawandel-beeinflusst-die-migration-aber-nicht-immer-so-wie-man-denkt-das-beispiel-bangladesch/88891423) / [Bangladesh sheds light on climate change migration patterns](https://www.swissinfo.ch/eng/foreign-affairs/bangladesh-sheds-light-on-climate-change-migration-patterns/88942372?utm_source=multiple&utm_medium=website&utm_campaign=bundle-front1_en&utm_content=o&utm_term=wpblock_teaser-bundle)
</li>

<li>
<span class="media-outlet">Neue Zürcher Zeitung am Sonntag</span><span class="media-date">22 Dec 2024</span><br>
[«Unser Bild von Klimaflucht ist faktisch falsch. Trotzdem wird es von Politikern und Medien weiter verbreitet»](https://www.nzz.ch/wissenschaft/klimaflucht-narrativ-ist-faktisch-falsch-ld.1861230)
</li>

<li>
<span class="media-outlet">Süddeutsche Zeitung</span><span class="media-date">31 Aug 2024</span><br>
[Hungriger Fluss](https://www.sueddeutsche.de/projekte/artikel/wissen/klimaflucht-bangladesch-jamuna-e155165/?reduced=true)
</li>

<li>
<span class="media-outlet">Reportagen</span><span class="media-date">May 2024</span><br>
[Wenn der Fluss kommt](https://reportagen.com/reportage/wenn-der-fluss-kommt/)
</li>

<li>
<span class="media-outlet">Deutschlandfunk Nova</span><span class="media-date">28 Jan 2024</span><br>
[Manche Regionen in Bangladesch werden unbewohnbar](https://share.deutschlandradio.de/dlf-audiothek-audio-teilen.html?mdm:audio_id=dira_DRW_7c8c33fe)
</li>

<li>
<span class="media-outlet">Norddeutscher Rundfunk (NDR)</span><span class="media-date">13 Jan 2024</span><br>
[Bangladesh und der Klimawandel](https://www.ndr.de/nachrichten/info/Bangladesh-und-der-Klimawandel,audio1549170.html)
</li>

<li>
<span class="media-outlet">Neue Zürcher Zeitung</span><span class="media-date">2/5 Oct 2023</span><br>
[Wie reagiert man, wenn das eigene Hab und Gut immer wieder von einer Naturgewalt zerstört wird?](https://www.nzz.ch/wissenschaft/diese-menschen-leben-mit-der-staendigen-gefahr-alles-in-fluten-zu-verlieren-und-zeigen-wie-klima-migration-funktioniert-ld.1749807?reduced=true) / [If your home was repeatedly destroyed, how long would it take you to leave?](https://www.nzz.ch/english/villages-along-flood-prone-river-offer-new-climate-migration-insights-ld.1759247)
</li>

</ul>

## Podcasts

<ul class="media-list">

<li>
<span class="media-outlet">The Swiss Connection, SWI swissinfo.ch</span><span class="media-date">17 Mar 2026</span><br>
[Season 7, Episode 5: Climate solution series: how Bangladesh adapts to erosion, floods, and rising seas](https://www.buzzsprout.com/910414/episodes/18816081)
</li>

<li>
<span class="media-outlet">SciComm Palaver</span><span class="media-date">17 Mar 2025</span><br>
[Episode 39](https://sabinegysi.ch/scicomm-palaver-episode-39/)
</li>

<li>
<span class="media-outlet">Water Stressed Podcast</span><span class="media-date">24 Mar 2024</span><br>
[Listen](https://open.acast.com/public/streams/638b10408f875f00102f5aa8/episodes/660154257143f70017a27c6e.mp3)
</li>

</ul>

## TV & Video

<ul class="media-list">

<li>
<span class="media-outlet">Somoy TV</span><span class="media-date">21 Feb 2024</span><br>
[Watch on YouTube](https://www.youtube.com/watch?v=lKSQ3iwhjTM)
</li>

</ul>

## Documentary

<ul class="media-list">

<li>
<span class="media-outlet">Eroding Horizons: A Village on the Move</span><span class="media-date">2024</span><br>
A short documentary about research on riverbank erosion and migration in Bangladesh, co-created with filmmaker Anna Campert. Special Mention (Non-Fiction) at Earth 360° Fest of the Bangladesh Youth Environmental Initiative (BYEI).<br>
[Watch on YouTube](https://www.youtube.com/watch?v=d44LCujw6pk)
</li>

</ul>
